import { ApplicationConfig, provideZoneChangeDetection } from '@angular/core';
import { provideRouter } from '@angular/router';
import { provideAnimationsAsync } from '@angular/platform-browser/animations/async';
import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { routes } from './app.routes';
import { authInterceptor } from './modules/shared_module/interceptors/auth.interceptor';
import { provideToastr } from 'ngx-toastr';
import { FaIconLibrary } from '@fortawesome/angular-fontawesome';
import {
  faFile,
  faSave,
  faFolderOpen,
  faPlay,
  faSearchPlus,
  faSearchMinus,
  faExpand,
  faBolt,
  faGlobe,
  faCodeBranch,
  faCircle,
  faCode,
  faChevronLeft,
  faChevronRight,
  faTerminal,
  faTimes,
  faCog,
  faEdit,
  faTrash,
  faSpinner,
  faRocket,
  faCheckCircle,
  faShieldAlt,
  faChartLine,
  faUsers,
  faCloud,
  faArrowRight,
  faBars,
  faEnvelope,
  faLock,
  faUser,
  faHome,
  faSearch,
  faSignOutAlt,
  faChevronDown,
  faBell,
  faFilter,
  faPlus,
  faArrowLeft,
  faUndo,
} from '@fortawesome/free-solid-svg-icons';

export const appConfig: ApplicationConfig = {
  providers: [
    provideZoneChangeDetection({ eventCoalescing: true }),
    provideRouter(routes),
    provideAnimationsAsync(),
    provideHttpClient(withInterceptors([authInterceptor])),
    provideToastr({
      timeOut: 3000,
      positionClass: 'toast-top-right',
      preventDuplicates: true,
      closeButton: true,
      progressBar: true,
    }),
    {
      provide: FaIconLibrary,
      useFactory: () => {
        const library = new FaIconLibrary();
        library.addIcons(
          faFile,
          faSave,
          faFolderOpen,
          faPlay,
          faSearchPlus,
          faSearchMinus,
          faExpand,
          faBolt,
          faGlobe,
          faCodeBranch,
          faCircle,
          faCode,
          faChevronLeft,
          faChevronRight,
          faTerminal,
          faTimes,
          faCog,
          faEdit,
          faTrash,
          faSpinner,
          faRocket,
          faCheckCircle,
          faShieldAlt,
          faChartLine,
          faUsers,
          faCloud,
          faArrowRight,
          faBars,
          faEnvelope,
          faLock,
          faUser,
          faHome,
          faSearch,
          faSignOutAlt,
          faChevronDown,
          faBell,
          faFilter,
          faPlus,
          faArrowLeft,
          faUndo
        );
        return library;
      },
    },
  ],
};
