package com.workflow.auth.model;

import com.workflow.dto.UserDto;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class UserCreationResponse {
    private UserDto user;
    private String password; // Only populated if password was auto-generated
    private boolean passwordAutoGenerated;
}
